-- 30건의 일반문의 샘플 데이터 삽입
INSERT INTO general_inquiries (
    inquiry_number, 
    title, 
    content, 
    requester_id, 
    department, 
    status, 
    created_at,
    answer,
    answered_at,
    answered_by,
    is_secret
) VALUES 
-- 답변 완료된 문의 (20건)
('INQ-2025-001', 'System Login Issue', 'Cannot login to the system today. Changed password multiple times but still getting login errors.', (SELECT id FROM users WHERE email = 'user1@company.com' LIMIT 1), 'Sales Team', 'answered', '2025-09-20 09:30:00', 'Login issue resolved. Account was temporarily locked. Account has been activated, please try again.', '2025-09-20 14:15:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-002', 'Printer Connection Error', 'Conference room printer cannot connect. Please check network settings.', (SELECT id FROM users WHERE email = 'user2@company.com' LIMIT 1), 'Marketing Team', 'answered', '2025-09-21 10:15:00', 'Printer driver updated and network settings reconfigured. It should work normally now.', '2025-09-21 16:30:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-003', 'Email Account Problem', 'Not receiving emails. External emails seem to be blocked.', (SELECT id FROM users WHERE email = 'user3@company.com' LIMIT 1), 'HR Team', 'answered', '2025-09-22 11:00:00', 'Spam filter settings adjusted. External emails should now be received normally.', '2025-09-22 15:45:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-004', 'Software Installation Request', 'Need to install new project management software. What procedures should I follow?', (SELECT id FROM users WHERE email = 'user4@company.com' LIMIT 1), 'Development Team', 'answered', '2025-09-23 14:20:00', 'Software installation procedures have been provided. IT team will install it directly.', '2025-09-23 16:45:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-005', 'Password Reset', 'Forgot my password. Please reset it.', (SELECT id FROM users WHERE email = 'user5@company.com' LIMIT 1), 'Finance Team', 'answered', '2025-09-24 09:45:00', 'Password has been reset. New password has been delivered personally.', '2025-09-24 11:30:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-006', 'Network Speed Issue', 'Internet speed is very slow. Please check the network.', (SELECT id FROM users WHERE email = 'user6@company.com' LIMIT 1), 'Operations Team', 'answered', '2025-09-24 16:30:00', 'Network check completed. Router settings optimized and speed improved.', '2025-09-25 10:15:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-007', 'Data Backup Inquiry', 'Need information about backup methods for important data.', (SELECT id FROM users WHERE email = 'user7@company.com' LIMIT 1), 'Management', 'answered', '2025-09-19 15:30:00', 'Data backup procedures and policies have been explained personally.', '2025-09-20 11:00:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), true),
('INQ-2025-008', 'Meeting Room Booking System Error', 'Error in meeting room booking system. Cannot make reservations properly.', (SELECT id FROM users WHERE email = 'user1@company.com' LIMIT 1), 'Sales Team', 'answered', '2025-09-18 13:20:00', 'Meeting room booking system bug fixed. You can now make reservations normally.', '2025-09-19 09:30:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-009', 'Monitor Screen Flickering', 'Monitor screen keeps flickering. It hurts my eyes and makes work difficult.', (SELECT id FROM users WHERE email = 'user2@company.com' LIMIT 1), 'Marketing Team', 'answered', '2025-09-17 14:45:00', 'Monitor cable replaced and graphics driver updated. Flickering issue resolved.', '2025-09-18 10:20:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-010', 'Office Supply Order System', 'Cannot access office supply order system. Need urgent supplies.', (SELECT id FROM users WHERE email = 'user3@company.com' LIMIT 1), 'HR Team', 'answered', '2025-09-16 11:30:00', 'System access issue resolved. Phone orders are also temporarily available.', '2025-09-16 15:45:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-011', 'Development Server Access Issue', 'Cannot SSH to development server. Project progress is hindered.', (SELECT id FROM users WHERE email = 'user4@company.com' LIMIT 1), 'Development Team', 'answered', '2025-09-15 16:00:00', 'Server firewall settings adjusted. You can now access normally.', '2025-09-16 08:30:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-012', 'Finance System Permission Request', 'Need access permission for finance system. Please approve.', (SELECT id FROM users WHERE email = 'user5@company.com' LIMIT 1), 'Finance Team', 'answered', '2025-09-14 10:15:00', 'Finance system access permission granted. Set with limited permissions for security.', '2025-09-14 14:20:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-013', 'Operations System Monitoring', 'Want to learn how to use operations system monitoring tools.', (SELECT id FROM users WHERE email = 'user6@company.com' LIMIT 1), 'Operations Team', 'answered', '2025-09-13 15:30:00', 'Educational materials for monitoring tools provided. Contact us for additional questions.', '2025-09-14 09:15:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-014', 'Security Policy Inquiry', 'Want detailed information about company security policies.', (SELECT id FROM users WHERE email = 'user7@company.com' LIMIT 1), 'Management', 'answered', '2025-09-12 09:45:00', 'Security policy documents delivered personally. Contact us anytime for additional questions.', '2025-09-12 16:30:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), true),
('INQ-2025-015', 'Keyboard Malfunction', 'Keyboard suddenly stopped working. Needs replacement.', (SELECT id FROM users WHERE email = 'user8@company.com' LIMIT 1), 'Management', 'answered', '2025-09-11 14:20:00', 'Replaced with new keyboard. You can now use it normally.', '2025-09-12 10:00:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-016', 'Website Access Error', 'Cannot access company website. Getting 404 errors.', (SELECT id FROM users WHERE email = 'user2@company.com' LIMIT 1), 'Marketing Team', 'answered', '2025-09-10 08:45:00', 'Web server configuration issue resolved. You can now access normally.', '2025-09-10 12:30:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-017', 'Data Analysis Tools', 'Want to learn how to use data analysis tools.', (SELECT id FROM users WHERE email = 'user3@company.com' LIMIT 1), 'HR Team', 'answered', '2025-09-09 14:20:00', 'Training on data analysis tools conducted. Contact us for additional questions.', '2025-09-10 10:15:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-018', 'Code Repository Access', 'Need access permission for Git repository.', (SELECT id FROM users WHERE email = 'user4@company.com' LIMIT 1), 'Development Team', 'answered', '2025-09-08 16:30:00', 'Git repository access permission granted. SSH key setup also completed.', '2025-09-09 09:00:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),
('INQ-2025-019', 'Financial Report Generation', 'Error in financial report generation system.', (SELECT id FROM users WHERE email = 'user5@company.com' LIMIT 1), 'Finance Team', 'answered', '2025-09-07 11:15:00', 'Financial report generation system bug fixed. It now works normally.', '2025-09-07 16:45:00', (SELECT id FROM users WHERE email = 'service@itsm.com' LIMIT 1), false),
('INQ-2025-020', 'System Monitoring', 'No alerts from system monitoring tools.', (SELECT id FROM users WHERE email = 'user6@company.com' LIMIT 1), 'Operations Team', 'answered', '2025-09-06 13:45:00', 'Monitoring tool alert settings checked and fixed. Alerts now sent normally.', '2025-09-07 08:30:00', (SELECT id FROM users WHERE email = 'admin@itsm.com' LIMIT 1), false),

-- 답변 대기 중인 문의 (10건)
('INQ-2025-021', 'Security Related Inquiry', 'Have questions about system security policies. Please contact me personally.', (SELECT id FROM users WHERE email = 'user7@company.com' LIMIT 1), 'Management', 'pending', '2025-09-25 10:00:00', NULL, NULL, NULL, true),
('INQ-2025-022', 'New Software License', 'Need to purchase additional Adobe Creative Suite licenses.', (SELECT id FROM users WHERE email = 'user2@company.com' LIMIT 1), 'Marketing Team', 'pending', '2025-09-25 11:30:00', NULL, NULL, NULL, false),
('INQ-2025-023', 'Remote Work System', 'Want to know how to access VPN for remote work.', (SELECT id FROM users WHERE email = 'user1@company.com' LIMIT 1), 'Sales Team', 'pending', '2025-09-25 13:15:00', NULL, NULL, NULL, false),
('INQ-2025-024', 'Database Backup', 'Need backup for important project data.', (SELECT id FROM users WHERE email = 'user4@company.com' LIMIT 1), 'Development Team', 'pending', '2025-09-25 14:45:00', NULL, NULL, NULL, false),
('INQ-2025-025', 'Accounting System Update', 'Some functions not working after accounting system update.', (SELECT id FROM users WHERE email = 'user5@company.com' LIMIT 1), 'Finance Team', 'pending', '2025-09-25 15:20:00', NULL, NULL, NULL, false),
('INQ-2025-026', 'Server Performance Optimization', 'Web server response speed has slowed down. Need performance optimization.', (SELECT id FROM users WHERE email = 'user6@company.com' LIMIT 1), 'Operations Team', 'pending', '2025-09-25 16:10:00', NULL, NULL, NULL, false),
('INQ-2025-027', 'Mobile App Development Environment', 'Need to set up development environment for mobile app development.', (SELECT id FROM users WHERE email = 'user4@company.com' LIMIT 1), 'Development Team', 'pending', '2025-09-24 17:30:00', NULL, NULL, NULL, false),
('INQ-2025-028', 'Cloud Storage Capacity', 'Cloud storage capacity insufficient. Need expansion.', (SELECT id FROM users WHERE email = 'user3@company.com' LIMIT 1), 'HR Team', 'pending', '2025-09-24 18:00:00', NULL, NULL, NULL, false),
('INQ-2025-029', 'Security Training Request', 'Please conduct security training for employees.', (SELECT id FROM users WHERE email = 'user8@company.com' LIMIT 1), 'Management', 'pending', '2025-09-24 19:15:00', NULL, NULL, NULL, true),
('INQ-2025-030', 'Project Management Tool', 'Reviewing introduction of new project management tool.', (SELECT id FROM users WHERE email = 'user1@company.com' LIMIT 1), 'Sales Team', 'pending', '2025-09-23 20:30:00', NULL, NULL, NULL, false);

-- 삽입된 데이터 확인
SELECT inquiry_number, title, department, status, created_at, answered_at, is_secret FROM general_inquiries ORDER BY created_at DESC;
